spring:
  spring:
    datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://sqlserver-arya.database.windows.net:1433;database=aryadb;user=admsql@sqlserver-arya;password=devops@Fiap2tds;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      username: admsql
      password: devops@Fiap2tds

    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true



  ai:
    model:
      chat: DeepSeek-R1
    azure:
      openai:
        api-key: EO4QYkYu6S9TslvPXHA4fAmqwS1bdwYn74FS3ZonE02RBuN8qipnJQQJ99BEACfhMk5XJ3w3AAAAACOGjlDk
        endpoint: https://mr553-mak5nrtw-swedencentral.cognitiveservices.azure.com/
        chat:
          options:
            deployment-name: DeepSeek-R1
            temperature: 0.7
            api-version: 2025-05-12

  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000

openweather:
  api-key: da377d5c2b5c5aff6622436623211cec



api:
  security:
    jwt:
      secret: your_secret_key_here


opencage:
  api:
    key: a87244001db4445183d0c3ad9b0ce9d2